
talk1.pdf : latex/talk1.tex
	pdflatex latex/talk1.tex

latex/talk1.tex : talk1.lagda
	agda --allow-unsolved-metas --latex -i . -i /u/sabry/include/agda2/src talk1.lagda

talk2.pdf : latex/talk2.tex
	pdflatex latex/talk2.tex

latex/talk2.tex : talk2.lagda
	agda --allow-unsolved-metas --latex -i . -i /u/sabry/include/agda2/src talk2.lagda

talk3.pdf : latex/talk3.tex
	pdflatex latex/talk3.tex

latex/talk3.tex : talk3.lagda
	agda --allow-unsolved-metas --latex -i . -i /u/sabry/include/agda2/src talk3.lagda

